name: Deploy ML App

on:
  push:
    branches:
      - main
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login \
          --username AWS \
          --password-stdin ${{ secrets.ECR_URI }}

      - name: Build Docker image
        run: docker build -t studentperformance .

      - name: Push to ECR
        run: |
          docker tag studentperformance:latest ${{ secrets.ECR_URI }}:latest
          docker push ${{ secrets.ECR_URI }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.ECR_URI }}:latest
            docker stop studentperformance || true
            docker run -d -p 80:5000 \
            --name studentperformance \
            ${{ secrets.ECR_URI }}:latest